### ISSUE TITLE
Add tests and `ruff` execution to GitHub Actions

### ISSUE THREAD

**Issue by GabLeRoux** [Flexonze/django-auto-actions#3]
To improve code quality and catch issues early, we should add the following to the GitHub Actions workflow:

1. **Run tests**: Ensure all tests are executed automatically on each push or pull request.
2. **Ruff linting**: Integrate `ruff` to enforce consistent code style and catch linting errors.

**Goal:** Update the GitHub Actions configuration to run both tests and `ruff` on each CI run.

**Comment by hammadarshad1** [comment]
It's a very great suggestion from @GabLeRoux. I can help you with this, by adding the necessary actions. Its also a good starter for me to start contributing to this cool project @Flexonze.

**Comment by GabLeRoux** [comment]
Most of the work is already done in #1 for this current issue, but here are some other ideas that will also improve this project:

1. Add a build and publish step that will automatically do these things (when on a tag or a branch like `release/x.x.x`:
    1. Execute the desired commands to prepare the package
    2. Package the library
    3. Create a Github Release with automatic description (we can use https://github.com/softprops/action-gh-release with `generate_release_notes` set to true, it works very well)
    4. Publish the library on Pypy
2. Add an action that will automatically reply to the pull-request with coverage results (increase and decrease, etc.)
    1. I think this one is good and allows doing it with `coveralls` https://github.com/marocchino/sticky-pull-request-comment
  
🙏

**Comment by Flexonze** [comment]
Hey @hammadarshad1! @GabLeRoux has already taken care of it, but your contribution is more than welcome! I've added a bunch of issues that would be useful if you want to take a look, or feel free to open your own issues. :smile:

**Comment by hammadarshad1** [comment]
> Hey @hammadarshad1! @GabLeRoux has already taken care of it, but your contribution is more than welcome! I've added a bunch of issues that would be useful if you want to take a look, or feel free to open your own issues. 😄

I'll quickly look for new issues. I would definitely love to contribute. Thanks
